version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 527222548725.dkr.ecr.us-west-2.amazonaws.com
          aws-access-key-id: AKIAXVQHJVD26MFIQDUZ
          aws-secret-access-key: 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
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: config-server
          tag: "$CIRCLE_SHA1"